### ISSUE TITLE
Consecutive Start Stop Bug for Multiple Islands (Multiple STLs)

### ISSUE THREAD

**Issue by AESjay** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#109]
## Expected Behavior
Each island (each STL) would increment the start/stop location by the consecutive distance. 

## Actual Behavior
One STL seems to more-or-less work alright, while the start/stops for the other STL just hover around the same location.

## Possible Solution
Algorithm modification.

## Steps to Reproduce the Problem
Open the attached project file. Ensure Profile->Optimizations is set to "least recently visited" and "consecutive" and 2 inches.

[Consecutive Start Stop Bug.zip](https://github.com/mdfbaam/ORNL-Slicer-2-Issue-Tracker/files/10456379/Consecutive.Start.Stop.Bug.zip)

**Comment by aroschli** [comment]
Moved to new tracker.
