### ISSUE TITLE
Consecutive Start Stop Increments on Index Point rather than Absolute XY value

### ISSUE THREAD

**Issue by AESjay** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#110]
## Expected Behavior
Start/stop location will be at least as far apart as set in "Consecutive Distance Threshold" setting.

## Actual Behavior
Sometimes start stops are exactly on top of each other, or only spaced apart by less than the threshold distance. For example, in the attached project, layers 23-24, and layers 25-26, and layers 39-40, the start stop is right on top of each other.  Layers 26 to 34 the start stop is staggered, but only by maybe 1/4" when the threshold is set to 1".  This is true even though the geometry only changes slightly from layer to layer.

## Possible Solution
Modify the algorithm to work on XY coordinates in the gcode rather than an "N" index point within the layer.  Or, if this is computationally intensive, enable a user checkbox to do this and the user would have to understand that it will take longer to slice then.  

## Steps to Reproduce the Problem
Open the project file and slice.   View the gcode and scroll through the layers.  

[Consec Start Stop Single STL Increment Not Enough2.zip](https://github.com/mdfbaam/ORNL-Slicer-2-Issue-Tracker/files/10456787/Consec.Start.Stop.Single.STL.Increment.Not.Enough2.zip)
![SS Consec ends on top of each other](https://user-images.githubusercontent.com/97554389/213446019-c8187bf4-3ea9-41a7-88eb-55ec32f0aea9.jpg)

**Comment by aroschli** [comment]
Moved to new tracker
