### ISSUE TITLE
Layer times don't calculate correctly when using spiralize

### ISSUE THREAD

**Issue by AESjay** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#111]
## Expected Behavior
Similar layer times are output for spiralize versus regular slicing (maybe a hair quicker since it wouldn't have tip wipes and travel moves).

## Actual Behavior
Layer times seem to not make sense and vary wildly.    

## Possible Solution
Check into how layer times are calculated when spiralize is activated.

## Steps to Reproduce the Problem
Layer times output from the same file slicing with and without spiralize.  Also project file attached.  

[Layer Times - Spiralize.zip](https://github.com/mdfbaam/ORNL-Slicer-2-Issue-Tracker/files/10514617/Layer.Times.-.Spiralize.zip)

**Comment by aroschli** [comment]
Bug exists for CI Syntax only.
