### ISSUE TITLE
Infill Pattern and Infill Density buttons do not work

### ISSUE THREAD

**Issue by ericblack04** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#12]
## Expected Behavior
Allow user to change values.

## Actual Behavior
Not able to click on or edit parameters.

## Possible Solution
Self-Explanatory

## Steps to Reproduce the Problem
Self-Explanatory.  Ideally, bullet or numbered list.

## Specifications
Platform, machine specs, anything else you think might be relevant.

# Labels (delete this section once you've selected labels)
Your issue must contain three labels from specific categories.  For an explanation, please check out the Wiki using the navigation above.  Or, you can use the link here: https://github.com/mdfbaam/ORNL-Slicer-2-Issue-Tracker/wiki

**Comment by mr-glt** [comment]
Infill density setting fixed by automatically calculating line spacing. The user can also choose to override the calculated line spacing if they wish to. Infill patterns are also working.
