### ISSUE TITLE
Drag n Drop Vertices

### ISSUE THREAD

**Issue by AESjay** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#122]
Feature Request:
After slicing, when viewing Gcode, it would be optimal to toggle on a "Visual Edit Mode", where the user could select vertices in the gcode preview, and drag them to new locations.  It may even be helpful to have a "snap to" grid of a user specified size, so it would snap to the closest point on that grid.  

The overall purpose would be to make hand editing gcode much easier and less labor intensive. 

Example image below:
![image](https://github.com/mdfbaam/ORNL-Slicer-2-Issue-Tracker/assets/97554389/6d5b912f-c0fa-4d81-af0a-781a0c579f98)

**Comment by AESjay** [comment]
Feature Request

**Comment by aroschli** [comment]
Moved to new tracker
