### ISSUE TITLE
Visualization Slider can go negative

### ISSUE THREAD

**Issue by AESjay** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#126]
## Expected Behavior
"First Segment" and "Last Segment" box should stop at zero.

## Actual Behavior
Sometimes when sliding the bars to the left with the mouse, the boxes will display a "-1" segment, and then if you slide the bottom bar back to the right, the visualization does not come back.  You have adjust a different slider to get it back to zero or positive before it will display any preview.  

## Possible Solution
Check for negative numbers and stop at zero.

## Steps to Reproduce the Problem
Self-Explanatory.  

![display value bug](https://github.com/mdfbaam/ORNL-Slicer-2-Issue-Tracker/assets/97554389/e76e8cb2-6ad6-41df-a58a-5bbeeccd11f8)

**Comment by AESjay** [comment]
Low Priority, Visualization, Bug fix

**Comment by AESjay** [comment]
Seems to happen when viewing some layers and grabbing the slider button with the mouse.  Does not always happen on layer 1 but if you slide the layer up to another layer, then grab the segment slider with the mouse, it usually can be moved to -1.

**Comment by aroschli** [comment]
Moved to new tracker
