### ISSUE TITLE
Feature Request - Save Project Warning when closing

### ISSUE THREAD

**Issue by AESjay** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#127]
## Expected Behavior
Slicer2 would initiate a pop-up asking the user if they want to save the project if any changes have been made.  

## Actual Behavior
Slicer just closes.  

## Possible Solution
Self-Explanatory

## Steps to Reproduce the Problem
Self-Explanatory.  Ideally, bullet or numbered list.

## Specifications
Platform, machine specs, anything else you think might be relevant.

**Comment by aroschli** [comment]
Moved to new tracker
