### ISSUE TITLE
Reinstate purge duration and location control for minimum layer times

### ISSUE THREAD

**Issue by AESnick** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#133]
## Feature
When using purge to meet minimum layer times, re-enable the ability to specify purge duration vs dwell time, as well as dwell location.

## Expected Behavior
This feature allows for the purge time to be set for a dwell-enabled minimum layer time, allowing independent adjustment of the purge time. ie, set a 15 second purge time, and the rest of the time required to meet the minimum layer time will be dwelling in a 'parked' location. The park location was previously either 'XYZ home', or the standard 'purge' location.

This feature exists in Slicer 1, and previously existed in Slicer 2.

**Comment by aroschli** [comment]
Issue has been resolved
