### ISSUE TITLE
Open Website/Repository/Report Bug Help buttons link to the wrong Github page

### ISSUE THREAD

**Issue by ericblack04** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#135]
## Expected Behavior
Click on Report Bug to be brough to this ORNL Slicer 2 Issue Tracker github.

## Actual Behavior
Link is to ORNL Slicer/Slicer 2 which has not been active.

## Possible Solution
Update links.

## Steps to Reproduce the Problem
Self-Explanatory.  Ideally, bullet or numbered list.

## Specifications
Platform, machine specs, anything else you think might be relevant.

**Comment by aroschli** [comment]
Issue has been resolved
