### ISSUE TITLE
Infill not generating to perimeter when inset is spawned only on some features.

### ISSUE THREAD

**Issue by cmdwyer3** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#137]
## Expected Behavior
If the inset minimum path length is set to exclude some paths from generating, the infill paths should continue to the perimeter rather than where the inset should have been.
![Screenshot 2023-12-11 131341](https://github.com/mdfbaam/ORNL-Slicer-2-Issue-Tracker/assets/113203630/69f5c5dc-6c5a-459f-ba24-bb2a91589cc1)

## Actual Behavior
The inset does not generate (as designed); however, the infill generates the same no matter if insets are present or not.

## Possible Solution
Have infill generate after insets vs before? Not sure.

## Steps to Reproduce the Problem
Create a part with a few holes. Set perimeters and insets to 1 path each with infill to 100%. Increase the minimum path length for insets until some insets around the holes do not generate. Notice the gaps between infill and perimeters around those holes as if the inset is still generating and then being removed without adjusting the infill.

## Specifications
JB3D P3-44 templates, windows 11, Slicer 2 beta v 0.99.8. Project file attached.
[Inset Infill Path Generation.zip](https://github.com/mdfbaam/ORNL-Slicer-2-Issue-Tracker/files/13639598/Inset.Infill.Path.Generation.zip)

**Comment by aroschli** [comment]
Moved to new tracker
