### ISSUE TITLE
Spirialize and Cooling do not work together

### ISSUE THREAD

**Issue by AESnick** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#138]
## Expected Behavior
When slicing a print with cooling enabled (slowdown) and using the spiralize feature, slicer should modify extruder speed to match the change in feedrate speed.

## Actual Behavior
Extruder speed is set at L1 and does not update, while feedrate changes every layer.

## Possible Solution
As above.

## Steps to Reproduce the Problem
Spiralized part with 60s min layer time.
![image](https://github.com/mdfbaam/ORNL-Slicer-2-Issue-Tracker/assets/146254494/661f6cd2-ebec-4da6-8c83-388226fe2c19)

Gcode from slice:
(BEGINNING LAYER: 1)
...
G1 F30.6176 S3.8636 X164.7180 Y67.6833 W-0.0007 (PERIMETER)
...
BEGINNING LAYER: 376)
M1 (OPTIONAL STOP - LAYER CHANGE)

(Nozzle 0)
G1 F101.0882 X157.7640 Y61.5515 W-18.7508 (PERIMETER)

## Specifications
0.99.8 11-11-23

**Comment by aroschli** [comment]
Issue has been fixed
