### ISSUE TITLE
Wireframe - Show Edges

### ISSUE THREAD

**Issue by aroschli** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#15]
## Expected Behavior
When enabled, the edges of each triangle in each STL will be colored such that they are very easy to see. 

## Actual Behavior
Show wireframe does nothing

## Possible Solution
Change the color of each edge when drawing them in the visualizer

## Steps to Reproduce the Problem
N/A

## Specifications
Needs to make the edges of each triangle in the STL file very apparent/easy to see so that the user can tell the surface geometry.

**Comment by mr-glt** [comment]
Added an option to render an object as a wireframe from the right click menu
