### ISSUE TITLE
Update icon to reflect Slicer "2"

### ISSUE THREAD

**Issue by ericblack04** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#29]
## Expected Behavior
Self-Explanatory.

## Actual Behavior
Self-Explanatory

## Possible Solution
Maybe just put a nice "2" or "II" in the icon so I can tell them apart while I have both installed.

## Steps to Reproduce the Problem
Self-Explanatory.  Ideally, bullet or numbered list.

## Specifications
Platform, machine specs, anything else you think might be relevant.

**Comment by ericblack04** [comment]
I can't flair it with labels but Alex if you see this I think it's understood that this is low priority wishlist material!

**Comment by aroschli** [comment]
> I can't flair it with labels but Alex if you see this I think it's understood that this is low priority wishlist material!
