### ISSUE TITLE
User's Manual Doesn't Open in Installer

### ISSUE THREAD

**Issue by aroschli** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#31]
## Expected Behavior
User's Manual is available under the help menu

## Actual Behavior
Nothing...

## Possible Solution
Self-Explanatory

## Steps to Reproduce the Problem
Self-Explanatory

## Specifications
Platform, machine specs, anything else you think might be relevant.

**Comment by mborish** [comment]
Fixed in v.94
