### ISSUE TITLE
Ramping of speed in corners

### ISSUE THREAD

**Issue by aroschli** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#33]
## Expected Behavior
Emulation of mathematical speed scaling done by controller while cornering

## Actual Behavior
Self-Explanatory

## Possible Solution
Need to detect corners, based on a defined angle, and ramp speed down going into corner and up going out of corner

## Steps to Reproduce the Problem
Self-Explanatory.

## Specifications
Should work for all machine types on the polymer slicer

**Comment by tycrisp-hybridmanutech** [comment]
Hi, I'm encountering the same issue. Has this been addressed?
