### ISSUE TITLE
"Wait for User" Radio Button under "G-code" in Printer Settings bug

### ISSUE THREAD

**Issue by ericblack04** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#37]
## Expected Behavior
Un-check radio button for "wait for user", expected to remove M0 from Gcode.

## Actual Behavior
M0 code remains after purge when slicing even while un-checked.

## Possible Solution
Self-Explanatory

## Steps to Reproduce the Problem
Self-Explanatory.  Ideally, bullet or numbered list.

## Specifications
Platform, machine specs, anything else you think might be relevant.

**Comment by ericblack04** [comment]
Low priority bug.

**Comment by aroschli** [comment]
Fixed for v0.94
