### ISSUE TITLE
Loading Project puts STL off of screen and does not show g-code if sliced again.

### ISSUE THREAD

**Issue by ericblack04** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#38]
## Expected Behavior
Loaded an existing project, expected to see identical STL and settings.

## Actual Behavior
STL was not in viewing box, was able to "center part in build volume" but was then not able to interact with it. The translations showed very large numbers (in inches).

EDIT: In addition, after centering the part again and slicing, the g-code does not show in the visual window but does appear in the g-code editor.

## Possible Solution
Self-Explanatory

## Steps to Reproduce the Problem
Self-Explanatory.  Ideally, bullet or numbered list.

## Specifications
Platform, machine specs, anything else you think might be relevant.

**Comment by ericblack04** [comment]
Bug, cmake, high

**Comment by aroschli** [comment]
Fixed by @mborish in commit a74ba9d6e257fb6e5c4ec5c7fa0ca156e726c44b [a74ba9d]
