### ISSUE TITLE
Region Ordering does not seem to be active.

### ISSUE THREAD

**Issue by ericblack04** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#40]
## Expected Behavior
Set order to Infill > Inset > Perimeter.

## Actual Behavior
Exported G-code was ordered Perimeter > Inset > Infill.

## Possible Solution
Self-Explanatory

## Steps to Reproduce the Problem
Self-Explanatory.  Ideally, bullet or numbered list.

## Specifications
Platform, machine specs, anything else you think might be relevant.

**Comment by ericblack04** [comment]
Bug, core-slicing, medium.

**Comment by mborish** [comment]
Fixed.

**Comment by mborish** [comment]
Fix will appear in v.94 release.
