### ISSUE TITLE
Slicing Multiple STLs Bug

### ISSUE THREAD

**Issue by ericblack04** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#44]
## Expected Behavior
Slicer should slice multiple STLs without issue. Travel between two STLs should be:

Travel Lift Z
XY Travel
Travel Lower Z

## Actual Behavior
Extruder is moving to a different Z height within a layer when it moves to a different STL.

For example, my first layer is Z-4.5. The first Z travel and extrusion moves all take place at Z-4.5. However, when it goes to travel to the next STL, instead of it doing an expected lift, travel, lower, it does a lift, XYZ travel, then a lower.

## Possible Solution
Self-Explanatory

## Steps to Reproduce the Problem
Self-Explanatory.  Ideally, bullet or numbered list.

## Specifications
Platform, machine specs, anything else you think might be relevant.

**Comment by ericblack04** [comment]
Bug, core-gcode, high

**Comment by mborish** [comment]
Fix will appear in v.94 release.
