### ISSUE TITLE
Add slider bars for G-code viewing and manipulation similar to Slicer 1

### ISSUE THREAD

**Issue by ericblack04** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#61]
## Expected Behavior
Slicer 1 allowed for quick scrolling of layers using the slider bars that could be clicked on and dragged.

## Actual Behavior
The current implementation allows for individual clicking or scrolling with the mouse wheel but this can be tedious with thousands of layers. A slider bar would allow for very quick jumping around.

## Possible Solution
Slider bar from slicer 1 (bars for first layer shown and last layer shown).

## Steps to Reproduce the Problem
Self-Explanatory.  Ideally, bullet or numbered list.

## Specifications
Platform, machine specs, anything else you think might be relevant.

**Comment by ericblack04** [comment]
Core-gcode, feature, low priority

**Comment by ericblack04** [comment]
I also just realized I can type in what layer I want to go to...like I said low priority, but I still think it would be a nice quality of life thing.

**Comment by aroschli** [comment]
Goes along with #48

**Comment by ericblack04** [comment]
Ya know I thought I had mentioned something like this before but I didn't see it. You're right, I already asked about this in #48

**Comment by aroschli** [comment]
No worries. We will keep both of them open to reference as part of the redesign.
