### ISSUE TITLE
Add STL Length Unit in Preferences

### ISSUE THREAD

**Issue by ericblack04** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#66]
## Expected Behavior
Set the default length unit for imported STLs to inches. Slicer 1 had this option in preferences.

## Actual Behavior
To change the units on an STL, you must manually change the unit in the "scaling" toolbar.

## Possible Solution
Either add the option similar to Slicer 1, or make the global "Distance Unit" affect STLs as well.

## Steps to Reproduce the Problem
Self-Explanatory.  Ideally, bullet or numbered list.

## Specifications
Platform, machine specs, anything else you think might be relevant.

**Comment by ericblack04** [comment]
Core-ui, feature, low-priority

**Comment by mr-glt** [comment]
Added "Imported Model Unit" to preferences
