### ISSUE TITLE
Time estimate does not provide adjusted time when using force minimum layer time

### ISSUE THREAD

**Issue by AESjay** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#69]
## Expected Behavior
Slicer summary will give both estimated time and estimated adjusted time (similar to slicer 1).  

## Actual Behavior
Only the estimated time is given, but not the adjusted time.  So the actual print time will be much longer if cooling is on, forcing the layers to take longer.  

## Possible Solution
Add functionality back in, similar to slicer 1.

## Steps to Reproduce the Problem
Slice something using force minimum layer time and check the time estimate. 

## Specifications
Here's a screen shot example (Adjusted time: 69 layers at 3 minutes per layer = 207 minutes).  
![Layer times not adjusted](https://user-images.githubusercontent.com/97554389/149428737-e3a4c8f0-29b1-48b4-b6c4-1d5b1aea861f.jpg)

**Comment by aroschli** [comment]
Need to show total adjusted time in the status window and at the top of the layer times tab.
