### ISSUE TITLE
Unit system change in application preferences does not change output unit system

### ISSUE THREAD

**Issue by drewgrout** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#92]
Unit system change made in application preferences does change the units in printer settings as desired, but does not change the units beyond this. The units in the status do not change nor do the units in the gcode output.

**Comment by aroschli** [comment]
Hi @drewgrout thanks for submitting an issue. We will make the suggested change for the status window output units. Currently, those units match those in the g-code file definition. You asked to be able to change the units of the output g-code file, this is not something we support as we define the units for each syntax specific to the machine definition given to us by the OEM. Please feel free to email me if you have additional questions.
