### ISSUE TITLE
Scale, Rotate, Move values don't appear when in dark mode

### ISSUE THREAD

**Issue by d-portero** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#94]
## Expected Behavior
The values for the part size, current rotation, scaling appear when the button is clicked

## Actual Behavior
Blank spaces appear 

## Possible Solution
Self-Explanatory

## Steps to Reproduce the Problem
-Change to dark mode
-upload stl
-attempt to scale/rotate/move object

## Specifications
Beta Version 0.99.3
![image](https://user-images.githubusercontent.com/50592002/178624812-6cd20661-f109-45bf-a129-418cea9b2025.png)
![image](https://user-images.githubusercontent.com/50592002/178624818-763235e8-a7a7-4eb3-9011-b21c96fc26d5.png)
![image](https://user-images.githubusercontent.com/50592002/178624842-7699ef75-8798-45f5-bc6b-595b04a5b933.png)

**Comment by its-a-bee** [comment]
@d-portero, sorry for the late response. Can you tell me more about your computer/operating system? The UI elements you have identified display correctly on my machine, as shown below. 

![image](https://user-images.githubusercontent.com/77174534/184952852-9daed68b-1ea5-4f34-9320-a2920bcfb44e.png)

I'm not sure what could cause the discrepancy.

**Comment by d-portero** [comment]
The computer is a Lenovo laptop running windows 10. Intel i7 processor. Is there anything else you would like to know?

**Comment by its-a-bee** [comment]
We have been investigating on our end and it seems to be an issue with the installer. We will work to get this fixed asap. Thanks for reporting the issue.

**Comment by its-a-bee** [comment]
I believe this problem only occurred during sessions in which the theme was switched from Light to Dark. There was an issue when updating the theme mid-session that caused the specified submenus to not be colored correctly; it updated the text color to white, but did not update the background, causing the text to "disappear". When updating from Dark to Light, the Dark theme colors remained, which did not make the values disappear but did look a bit odd. 

For now -- if Slicer is exited in dark mode and then restarted, the menus and values should appear correctly. 

I have fixed the theme updating issue and in the next release this should be resolved.
