### ISSUE TITLE
Incorrect Weight with Custom Density

### ISSUE THREAD

**Issue by aroschli** [mdfbaam/ORNL-Slicer-2-Issue-Tracker#95]
## Expected Behavior
Self-Explanatory.

## Actual Behavior
Weight estimate is off by E15 when using a custom density value.

## Possible Solution
The conversion from the unit class is likely the suspect.

## Steps to Reproduce the Problem
Slice a part with a custom density value and the resultant weight will be a very small number.

## Specifications
N/A

**Comment by ericblack04** [comment]
Was about to report a new bug but I see you are already aware. We will use one of your presets for the time being as they seem to work just fine.
